services:
  db:
    image: postgres:15.10-alpine
    restart: "no"
    platform: linux/amd64
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - database:/var/lib/postgresql/data
    # command: [ "postgres", "-c", "log_statement=all" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 3s
      retries: 3
  backend:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - 127.0.0.1:8080:${BACKEND_PORT}
    volumes:
      - ./:/app
    env_file:
      - .env
      - .env.local

volumes:
  database: